services:
  database:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "${POSTGRES_LOCAL_PORT}:5432"
    networks:
      - ovitrine-network
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "${API_LOCAL_PORT:-3000}:3000"
    networks:
      - ovitrine-network
    depends_on:
      - database

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${CLIENT_LOCAL_PORT:-8080}:80"
    networks:
      - ovitrine-network
    depends_on:
      - api

  proxy:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api
      - web
    networks:
      - ovitrine-network

networks:
  ovitrine-network:

volumes:
  db_data:
