# Nom du workflow qui sera affiché sur Github
name: Run integration tests on API

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  run_api_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ovitrine_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ovitrine_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      # Appliquer les migrations Prisma
      - name: Run Prisma migrations
        run: npx prisma migrate deploy --schema=prisma/schema.prisma

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Build API
        run: npm run build

      # Insérer des données de test si mon test attend un tableau non vide
      - name: Seed database
        run: npx prisma db seed --schema=prisma/schema.prisma

      - name: Run tests
        run: npm run test
